connections {
    quanseq-left {
        version = 2
        proposals = aes256-sha256-mlkem1024
        local_addrs = 10.10.0.1
        remote_addrs = 10.10.0.2
        local {
            auth = psk
            id = left
        }
        remote {
            auth = psk
            id = right
        }
        children {
            net-left {
                esp_proposals = aes256-sha256
                local_ts = 10.10.0.1/32
                remote_ts = 10.10.0.2/32
                start_action = none
            }
        }
    }
    quanseq-right {
        version = 2
        proposals = aes256-sha256-mlkem1024
        local_addrs = 10.10.0.2
        remote_addrs = 10.10.0.1
        local {
            auth = psk
            id = right
        }
        remote {
            auth = psk
            id = left
        }
        children {
            net-right {
                esp_proposals = aes256-sha256
                local_ts = 10.10.0.2/32
                remote_ts = 10.10.0.1/32
                start_action = none
            }
        }
    }
}
secrets {
    ike-1 {
        id-left = left
        id-right = right
        secret = testpsk1234
    }
}
