connections {
    pqc-tunnel {
        version = 2
        proposals = aes256-sha256-mlkem1024
        local_addrs = 192.168.1.7
        remote_addrs = 192.168.1.6
        local {
            auth = psk
            id = vm-b
        }
        remote {
            auth = psk
            id = vm-a
        }
        children {
            net {
                esp_proposals = aes256-sha256
                local_ts = 192.168.1.7/32
                remote_ts = 192.168.1.6/32
                start_action = none
            }
        }
    }
}
secrets {
    ike-1 {
        id-1 = vm-a
        id-2 = vm-b
        secret = YOUR_IPSEC_PSK_HERE
    }
}
