"use client";

import { useCallback, useEffect, useState } from "react";
import {
  AlertTriangle, Check, Copy, KeyRound, Plus, ShieldAlert, Trash2, XCircle,
} from "lucide-react";
import {
  quansec, ApiKey, ApiKeyCreated, GrantableScopes, TLS_KEY_SCOPES, apiKeyState,
} from "@/lib/api";
import { Panel, PanelHeader, ConfirmDialog, DismissButton } from "@/components/ui-primitives";

/**
 * TLS API keys.
 *
 * An API key authenticates an APPLICATION to QUANSEC's TLS monitoring and
 * control APIs. It does not participate in any TLS handshake, does not carry
 * key material, and does not make a connection quantum-safe — the transport is
 * protected separately by whichever TLS policy is loaded. The page says so
 * rather than leaving the reader to assume otherwise.
 *
 * Three key systems exist in QUANSEC and only this one is user-managed:
 *   TLS handshake keys  generated by OpenSSL per handshake, never exposed
 *   Login tokens        short-lived JWT + rotating refresh, for people
 *   API keys            long-lived, revocable, for applications — this page
 */

/** 90 days matches DEFAULT_EXPIRY_DAYS in protocols/auth_api_keys.py. */
const EXPIRY_CHOICES: { days: number; label: string; isDefault?: boolean }[] = [
  { days: 30, label: "30 days" },
  { days: 90, label: "90 days", isDefault: true },
  { days: 180, label: "180 days" },
  { days: 365, label: "1 year" },
];

function relative(iso: string | null): string {
  if (!iso) return "Never";
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "Just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

function StateBadge({ keyRow }: { keyRow: ApiKey }) {
  const state = apiKeyState(keyRow);
  const style = {
    active: { c: "var(--pqc-cyan)", b: "var(--pqc-cyan-glow)", r: "var(--pqc-cyan-dim)" },
    expired: { c: "var(--threat-amber)", b: "var(--threat-amber-glow)", r: "var(--threat-amber-dim)" },
    revoked: { c: "var(--text-tertiary)", b: "var(--bg-panel-raised)", r: "var(--border-hairline)" },
  }[state];

  return (
    <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-mono-display font-semibold uppercase tracking-wider"
          style={{ color: style.c, background: style.b, border: `1px solid ${style.r}` }}>
      {state}
    </span>
  );
}

export default function TlsKeysPage() {
  const [keys, setKeys] = useState<ApiKey[] | null>(null);
  const [grantable, setGrantable] = useState<GrantableScopes | null>(null);
  const [error, setError] = useState<string | null>(null);

  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState("");
  const [scopes, setScopes] = useState<string[]>(["tls:read"]);
  const [expiryDays, setExpiryDays] = useState<number | null>(90);
  const [creating, setCreating] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const [revealed, setRevealed] = useState<ApiKeyCreated | null>(null);
  const [copied, setCopied] = useState(false);
  const [confirmRevoke, setConfirmRevoke] = useState<ApiKey | null>(null);

  const load = useCallback(async () => {
    try {
      const [k, g] = await Promise.all([
        quansec.listTlsApiKeys(),
        quansec.getGrantableScopes(),
      ]);
      setKeys(k);
      setGrantable(g);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load API keys");
      setKeys(null);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const canGrant = (scope: string) => grantable?.grantable.includes(scope) ?? false;
  const isSystemAdmin = canGrant("system:admin");

  const create = async () => {
    if (!name.trim() || scopes.length === 0) return;
    setCreating(true);
    setFormError(null);
    try {
      const created = await quansec.createTlsApiKey(name.trim(), scopes, {
        expiresInDays: expiryDays ?? undefined,
        neverExpires: expiryDays === null,
      });
      setRevealed(created);
      setName("");
      setScopes(["tls:read"]);
      setExpiryDays(90);
      setShowForm(false);
      await load();
    } catch (err) {
      // Surfaced inline rather than swallowed: a 403 here is the server
      // refusing a scope the caller does not hold, and the user needs to know
      // which one rather than seeing an empty form.
      setFormError(err instanceof Error ? err.message : "Key creation failed");
    } finally {
      setCreating(false);
    }
  };

  const revoke = async (key: ApiKey) => {
    try {
      await quansec.revokeTlsApiKey(key.id);
      setConfirmRevoke(null);
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Revoke failed");
      setConfirmRevoke(null);
    }
  };

  const copy = async () => {
    if (!revealed) return;
    await navigator.clipboard.writeText(revealed.api_key);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-8 max-w-6xl space-y-6">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-bold tracking-tight" style={{ color: "var(--text-primary)" }}>
            API keys
          </h1>
          <p className="text-sm mt-1 max-w-2xl" style={{ color: "var(--text-secondary)" }}>
            Use an API key to authenticate your application to QUANSEC TLS
            monitoring and control APIs. Network transport is protected
            separately by the configured TLS policy.
          </p>
        </div>
        <button onClick={() => { setShowForm((v) => !v); setFormError(null); }}
          className="inline-flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-bold focus-ring"
          style={{ background: "var(--pqc-cyan)", color: "#04231f" }}>
          <Plus size={13} strokeWidth={2.5} /> New key
        </button>
      </div>

      {error && (
        <div className="px-4 py-3 rounded-lg text-xs font-mono-display flex items-center gap-2"
             style={{ background: "var(--danger-glow)", color: "var(--danger-red)", border: "1px solid #7a1f33" }}>
          <XCircle size={14} /> {error}
        </div>
      )}

      {/* An API key is not key material. Stated once, prominently, because the
          conflation is the single most common misreading of this page. */}
      <div className="px-4 py-3 rounded-lg text-[11px] leading-relaxed flex gap-3"
           style={{ background: "var(--bg-panel-raised)", color: "var(--text-secondary)", border: "1px solid var(--border-hairline)" }}>
        <KeyRound size={15} className="shrink-0 mt-0.5" style={{ color: "var(--pqc-cyan-dim)" }} />
        <div>
          These keys authenticate <strong style={{ color: "var(--text-primary)" }}>applications
          to this API</strong>. They are not TLS handshake keys: those are
          generated by OpenSSL inside each handshake, are never stored, and are
          never displayed anywhere in QUANSEC. Holding a key does not make a
          connection quantum-safe.
        </div>
      </div>

      {/* ── Create form ─────────────────────────────────────────────────── */}
      {showForm && (
        <Panel>
          <PanelHeader eyebrow="Generate" title="New TLS API key" />
          <div className="px-5 py-4 space-y-5">
            {formError && (
              <div className="px-3.5 py-2.5 rounded-lg text-xs font-mono-display flex items-start gap-2"
                   style={{ background: "var(--danger-glow)", color: "var(--danger-red)", border: "1px solid #7a1f33" }}>
                <XCircle size={14} className="shrink-0 mt-0.5" /> {formError}
              </div>
            )}

            <div>
              <label className="block text-[10px] uppercase tracking-wider font-mono-display mb-1.5"
                     style={{ color: "var(--text-tertiary)" }}>Key name</label>
              <input value={name} onChange={(e) => setName(e.target.value)}
                placeholder="ci-enforcement-monitor"
                className="w-full px-3 py-2 rounded-lg text-sm font-mono-display focus-ring"
                style={{ background: "var(--bg-panel-raised)", color: "var(--text-primary)", border: "1px solid var(--border-hairline)" }} />
            </div>

            <div>
              <label className="block text-[10px] uppercase tracking-wider font-mono-display mb-2"
                     style={{ color: "var(--text-tertiary)" }}>Scopes</label>
              <div className="space-y-2">
                {TLS_KEY_SCOPES.map(({ scope, label, detail }) => {
                  const allowed = canGrant(scope);
                  const checked = scopes.includes(scope);
                  return (
                    <label key={scope}
                      className={`flex items-start gap-3 px-3 py-2.5 rounded-lg ${allowed ? "cursor-pointer" : "cursor-not-allowed opacity-50"}`}
                      style={{
                        background: checked ? "var(--pqc-cyan-glow)" : "var(--bg-panel-raised)",
                        border: `1px solid ${checked ? "var(--pqc-cyan-dim)" : "var(--border-hairline)"}`,
                      }}>
                      <input type="checkbox" disabled={!allowed} checked={checked}
                        onChange={(e) => setScopes((prev) =>
                          e.target.checked ? [...prev, scope] : prev.filter((s) => s !== scope))}
                        className="mt-0.5" />
                      <div className="min-w-0">
                        <div className="text-xs font-mono-display font-semibold"
                             style={{ color: checked ? "var(--pqc-cyan)" : "var(--text-primary)" }}>
                          {scope} <span style={{ color: "var(--text-tertiary)" }}>· {label}</span>
                        </div>
                        <div className="text-[11px] mt-0.5" style={{ color: "var(--text-secondary)" }}>
                          {detail}
                        </div>
                        {/* Shown rather than hidden: a user who cannot grant
                            tls:admin should see why, not find the option absent. */}
                        {!allowed && (
                          <div className="text-[10px] mt-1 font-mono-display" style={{ color: "var(--threat-amber)" }}>
                            Your account does not hold this scope, so it cannot be granted.
                          </div>
                        )}
                      </div>
                    </label>
                  );
                })}
              </div>
            </div>

            <div>
              <label className="block text-[10px] uppercase tracking-wider font-mono-display mb-2"
                     style={{ color: "var(--text-tertiary)" }}>Expires</label>
              <div className="flex flex-wrap gap-2">
                {EXPIRY_CHOICES.map(({ days, label, isDefault }) => (
                  <button key={days} onClick={() => setExpiryDays(days)}
                    className="px-3 py-1.5 rounded-lg text-[11px] font-mono-display focus-ring"
                    style={{
                      background: expiryDays === days ? "var(--pqc-cyan-glow)" : "var(--bg-panel-raised)",
                      color: expiryDays === days ? "var(--pqc-cyan)" : "var(--text-secondary)",
                      border: `1px solid ${expiryDays === days ? "var(--pqc-cyan-dim)" : "var(--border-hairline)"}`,
                    }}>
                    {label}{isDefault && " (default)"}
                  </button>
                ))}
                {/* Offered only to system:admin, and the server enforces it
                    regardless of what this button does. */}
                {isSystemAdmin && (
                  <button onClick={() => setExpiryDays(null)}
                    className="px-3 py-1.5 rounded-lg text-[11px] font-mono-display focus-ring"
                    style={{
                      background: expiryDays === null ? "var(--danger-glow)" : "var(--bg-panel-raised)",
                      color: expiryDays === null ? "var(--danger-red)" : "var(--text-secondary)",
                      border: `1px solid ${expiryDays === null ? "#7a1f33" : "var(--border-hairline)"}`,
                    }}>
                    Never
                  </button>
                )}
              </div>
              {expiryDays === null && (
                <div className="mt-2 px-3 py-2 rounded-lg text-[11px] leading-relaxed flex gap-2"
                     style={{ background: "var(--danger-glow)", color: "var(--danger-red)", border: "1px solid #7a1f33" }}>
                  <ShieldAlert size={14} className="shrink-0 mt-0.5" />
                  <span>
                    A non-expiring key is a permanent credential. If it leaks, it
                    stays valid until someone notices and revokes it. Prefer a
                    dated key and rotate it.
                  </span>
                </div>
              )}
            </div>

            <div className="flex items-center gap-2 pt-1">
              <button onClick={create} disabled={creating || !name.trim() || scopes.length === 0}
                className="px-3.5 py-2 rounded-lg text-xs font-bold focus-ring disabled:opacity-50"
                style={{ background: "var(--pqc-cyan)", color: "#04231f" }}>
                {creating ? "Generating…" : "Generate key"}
              </button>
              <button onClick={() => { setShowForm(false); setFormError(null); }}
                className="px-3.5 py-2 rounded-lg text-xs font-medium focus-ring"
                style={{ color: "var(--text-tertiary)", border: "1px solid var(--border-hairline)" }}>
                Cancel
              </button>
            </div>
          </div>
        </Panel>
      )}

      {/* ── One-time reveal ─────────────────────────────────────────────── */}
      {revealed && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-6"
             style={{ background: "rgba(0,0,0,0.72)" }}>
          <div className="w-full max-w-2xl rounded-2xl overflow-hidden"
               style={{ background: "var(--bg-panel)", border: "1px solid var(--pqc-cyan-dim)" }}>
            <div className="px-5 py-4 flex items-center justify-between border-b"
                 style={{ borderColor: "var(--border-hairline)" }}>
              <div className="flex items-center gap-2">
                <KeyRound size={16} style={{ color: "var(--pqc-cyan)" }} />
                <span className="text-sm font-bold" style={{ color: "var(--text-primary)" }}>
                  {revealed.name}
                </span>
              </div>
              <DismissButton onClick={() => setRevealed(null)} />
            </div>

            <div className="px-5 py-5 space-y-4">
              <div className="px-4 py-3 rounded-lg text-xs leading-relaxed flex gap-3"
                   style={{ background: "var(--threat-amber-glow)", color: "var(--threat-amber)", border: "1px solid var(--threat-amber-dim)" }}>
                <AlertTriangle size={16} className="shrink-0 mt-0.5" />
                <div>
                  <div className="font-bold font-mono-display mb-1">COPY THIS NOW</div>
                  {revealed.warning}
                </div>
              </div>

              <div className="flex items-stretch gap-2">
                <code className="flex-1 px-3 py-2.5 rounded-lg text-[11px] font-mono-display break-all"
                      style={{ background: "var(--bg-panel-raised)", color: "var(--pqc-cyan)", border: "1px solid var(--border-hairline)" }}>
                  {revealed.api_key}
                </code>
                <button onClick={copy}
                  className="px-3 rounded-lg focus-ring shrink-0"
                  style={{ background: copied ? "var(--pqc-cyan-glow)" : "var(--bg-panel-raised)",
                           color: copied ? "var(--pqc-cyan)" : "var(--text-secondary)",
                           border: "1px solid var(--border-hairline)" }}
                  aria-label={copied ? "Copied" : "Copy to clipboard"}
                  title="Copy to clipboard">
                  {copied ? <Check size={15} /> : <Copy size={15} />}
                </button>
              </div>

              <div className="text-[11px] font-mono-display space-y-1" style={{ color: "var(--text-tertiary)" }}>
                <div>scopes: <span style={{ color: "var(--text-secondary)" }}>{revealed.scopes.join(", ")}</span></div>
                <div>expires: <span style={{ color: "var(--text-secondary)" }}>
                  {revealed.expires_at ? new Date(revealed.expires_at).toLocaleDateString() : "never"}
                </span></div>
              </div>

              <div className="px-3.5 py-2.5 rounded-lg text-[11px] leading-relaxed"
                   style={{ background: "var(--bg-panel-raised)", color: "var(--text-secondary)", border: "1px solid var(--border-hairline)" }}>
                <div className="font-mono-display mb-1" style={{ color: "var(--text-tertiary)" }}>Use it:</div>
                <code className="block break-all" style={{ color: "var(--pqc-cyan)" }}>
                  curl -H &quot;Authorization: Bearer {revealed.key_prefix.split("...")[0]}…&quot; \<br />
                  &nbsp;&nbsp;https://localhost:8444/api/tls/status
                </code>
              </div>

              <button onClick={() => setRevealed(null)}
                className="w-full px-3.5 py-2 rounded-lg text-xs font-bold focus-ring"
                style={{ background: "var(--pqc-cyan)", color: "#04231f" }}>
                I have stored it
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Revoke confirmation ─────────────────────────────────────────── */}
      <ConfirmDialog
        open={confirmRevoke !== null}
        title={`Revoke ${confirmRevoke?.name}?`}
        description="Any application using this key stops working immediately. This cannot be undone — the key cannot be un-revoked or recovered, because only its hash was ever stored."
        confirmLabel="Revoke permanently"
        onConfirm={() => confirmRevoke && revoke(confirmRevoke)}
        onCancel={() => setConfirmRevoke(null)}
      />

      {/* ── Key list ────────────────────────────────────────────────────── */}
      <Panel>
        <PanelHeader eyebrow="Issued" title="TLS API keys"
          right={keys && (
            <span className="text-[10px] font-mono-display" style={{ color: "var(--text-tertiary)" }}>
              {keys.filter((k) => apiKeyState(k) === "active").length} active of {keys.length}
            </span>
          )} />

        {keys === null && !error ? (
          <p className="px-5 py-8 text-xs" style={{ color: "var(--text-tertiary)" }}>Loading…</p>
        ) : keys && keys.length === 0 ? (
          <p className="px-5 py-8 text-xs" style={{ color: "var(--text-tertiary)" }}>
            No TLS API key issued yet.
          </p>
        ) : (
          <div className="overflow-x-auto" tabIndex={0} role="region" aria-label="Scrollable table">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b" style={{ borderColor: "var(--border-hairline)" }}>
                  {["Name", "Key", "Scopes", "State", "Created", "Expires", "Last used", ""].map((h) => (
                    <th key={h} className="px-4 py-3 text-[10px] font-mono-display font-semibold uppercase tracking-wider whitespace-nowrap"
                        style={{ color: "var(--pqc-cyan-dim)" }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {(keys ?? []).map((k) => {
                  const state = apiKeyState(k);
                  return (
                    <tr key={k.id} className="border-b last:border-b-0"
                        style={{ borderColor: "var(--border-hairline)", opacity: state === "active" ? 1 : 0.55 }}>
                      <td className="px-4 py-2.5 text-xs font-semibold" style={{ color: "var(--text-primary)" }}>
                        {k.name}
                      </td>
                      {/* Masked by the backend. The raw value existed once. */}
                      <td className="px-4 py-2.5 text-xs font-mono-display" style={{ color: "var(--text-tertiary)" }}>
                        {k.key_prefix}
                      </td>
                      <td className="px-4 py-2.5 text-[11px] font-mono-display" style={{ color: "var(--text-secondary)" }}>
                        {k.scopes.join(", ")}
                      </td>
                      <td className="px-4 py-2.5"><StateBadge keyRow={k} /></td>
                      <td className="px-4 py-2.5 text-[11px] font-mono-display" style={{ color: "var(--text-tertiary)" }}>
                        {new Date(k.created_at).toLocaleDateString()}
                      </td>
                      <td className="px-4 py-2.5 text-[11px] font-mono-display"
                          style={{ color: k.expires_at ? "var(--text-tertiary)" : "var(--threat-amber)" }}>
                        {k.expires_at ? new Date(k.expires_at).toLocaleDateString() : "never"}
                      </td>
                      <td className="px-4 py-2.5 text-[11px] font-mono-display" style={{ color: "var(--text-tertiary)" }}>
                        {relative(k.last_used)}
                      </td>
                      <td className="px-4 py-2.5 text-right">
                        {state === "active" && (
                          <button onClick={() => setConfirmRevoke(k)}
                            className="p-1.5 rounded-lg focus-ring" title="Revoke"
                            style={{ color: "var(--danger-red)" }}>
                            <Trash2 size={14} />
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </div>
  );
}
